services:
  db:
    image: postgres:16-alpine
    container_name: commonground_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cgchecker
      POSTGRES_PASSWORD: cgchecker
      POSTGRES_DB: cgchecker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
